# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-24 02:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.CharField(max_length=100, verbose_name='target')),
                ('content', models.CharField(max_length=200, verbose_name='\u5185\u5bb9')),
                ('status', models.IntegerField(choices=[(1, '\u53ef\u7528'), (2, '\u5220\u9664')], default=1, verbose_name='\u72b6\u6001')),
                ('nickname', models.CharField(max_length=50, verbose_name='\u6635\u79f0')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('pid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='comments.Comment')),
            ],
            options={
                'verbose_name': '\u8bc4\u8bba',
                'verbose_name_plural': '\u8bc4\u8bba',
            },
        ),
    ]
