# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-16 12:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='\u540d\u79f0')),
                ('status', models.IntegerField(choices=[(1, '\u53ef\u7528'), (2, '\u5220\u9664')], default=1, verbose_name='\u72b6\u6001')),
                ('is_nav', models.BooleanField(default=False, verbose_name='\u662f\u5426\u4e3a\u5bfc\u822a')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u4f5c\u8005')),
            ],
            options={
                'verbose_name': '\u5206\u7c7b',
                'verbose_name_plural': '\u5206\u7c7b',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='\u6807\u9898')),
                ('desc', models.CharField(blank=True, max_length=255, verbose_name='\u6458\u8981')),
                ('content', models.TextField(help_text='\u6ce8:\u76ee\u524d\u4ec5\u652f\u6301markdown', verbose_name='\u5185\u5bb9')),
                ('status', models.IntegerField(choices=[(1, '\u4e0a\u7ebf'), (2, '\u8349\u7a3f'), (3, '\u5220\u9664')], default=1, verbose_name='\u72b6\u6001')),
                ('weight', models.IntegerField(default=0, verbose_name='\u6743\u91cd')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('pv', models.PositiveIntegerField(default=0, verbose_name='pv')),
                ('uv', models.PositiveIntegerField(default=0, verbose_name='uv')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='selfblog.Category', verbose_name='\u5206\u7c7b')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u4f5c\u8005')),
            ],
            options={
                'verbose_name': '\u6587\u7ae0',
                'verbose_name_plural': '\u6587\u7ae0',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='\u540d\u79f0')),
                ('status', models.IntegerField(choices=[(1, '\u6b63\u5e38'), (2, '\u5220\u9664')], default=1, verbose_name='\u72b6\u6001')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u4f5c\u8005')),
            ],
            options={
                'verbose_name': '\u6807\u7b7e',
                'verbose_name_plural': '\u6807\u7b7e',
            },
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(to='selfblog.Tag', verbose_name='\u6807\u7b7e'),
        ),
    ]
