# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-04-19 06:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selfblog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='weight',
            field=models.IntegerField(choices=[(1, '\u5426'), (2, '\u662f')], default=0, verbose_name='\u7f6e\u9876'),
        ),
    ]
