# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-04-20 00:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selfblog', '0002_auto_20180419_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(verbose_name='\u5185\u5bb9'),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.IntegerField(choices=[(1, '\u4e0a\u7ebf'), (2, '\u8349\u7a3f'), (3, '\u5220\u9664')], verbose_name='\u72b6\u6001'),
        ),
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(blank=True, to='selfblog.Tag', verbose_name='\u6807\u7b7e'),
        ),
        migrations.AlterField(
            model_name='post',
            name='weight',
            field=models.IntegerField(choices=[(1, '\u5426'), (2, '\u662f')], verbose_name='\u7f6e\u9876'),
        ),
    ]
