# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-04-20 02:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selfblog', '0003_auto_20180420_0845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='weight',
            field=models.IntegerField(choices=[(0, '\u5426'), (1, '\u662f')], verbose_name='\u7f6e\u9876'),
        ),
    ]
