# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-04-23 13:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selfblog', '0005_auto_20180420_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=30, verbose_name='\u540d\u79f0'),
        ),
    ]
