# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-16 12:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='\u7f51\u7ad9\u540d')),
                ('href', models.URLField(verbose_name='\u94fe\u63a5')),
                ('status', models.IntegerField(choices=[(1, '\u6b63\u5e38'), (2, '\u5220\u9664')], default=1, verbose_name='\u72b6\u6001')),
                ('weight', models.IntegerField(default=1, verbose_name='\u6743\u91cd')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u4f5c\u8005')),
            ],
            options={
                'verbose_name': '\u53cb\u94fe',
                'verbose_name_plural': '\u53cb\u94fe',
            },
        ),
        migrations.CreateModel(
            name='SideBar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='\u6807\u9898')),
                ('display_type', models.IntegerField(choices=[(1, 'notices'), (2, 'recently_post'), (3, 'hot_post'), (4, 'recently_comment')], default=1, verbose_name='\u5c55\u793a\u7c7b\u578b')),
                ('content', models.CharField(blank=True, help_text='\u975eHTML\u7c7b\u578b\uff0c\u53ef\u4ee5\u4e0d\u586b', max_length=500, verbose_name='\u5185\u5bb9')),
                ('status', models.IntegerField(choices=[(1, '\u5c55\u793a'), (2, '\u4e0b\u7ebf')], default=1, verbose_name='\u72b6\u6001')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u4f5c\u8005')),
            ],
            options={
                'verbose_name': '\u4fa7\u8fb9\u680f',
                'verbose_name_plural': '\u4fa7\u8fb9\u680f',
            },
        ),
    ]
