# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-12 06:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0003_auto_20180309_0936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sidebar',
            name='display_type',
            field=models.IntegerField(choices=[(1, 'notices'), (2, 'recently_post'), (3, 'hot_post'), (4, 'recently_comment')], default=1, verbose_name='\u5c55\u793a\u7c7b\u578b'),
        ),
    ]
